repos:
  - repo: local
    hooks:
      - id: run-go-tests
        name: Run Go Tests
        entry: make test
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
