// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: src/proto/balancer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoBalancer_GetRedirect_FullMethodName = "/balancer.VideoBalancer/GetRedirect"
)

// VideoBalancerClient is the client API for VideoBalancer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoBalancerClient interface {
	GetRedirect(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*VideoResponse, error)
}

type videoBalancerClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoBalancerClient(cc grpc.ClientConnInterface) VideoBalancerClient {
	return &videoBalancerClient{cc}
}

func (c *videoBalancerClient) GetRedirect(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (*VideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoResponse)
	err := c.cc.Invoke(ctx, VideoBalancer_GetRedirect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoBalancerServer is the server API for VideoBalancer service.
// All implementations must embed UnimplementedVideoBalancerServer
// for forward compatibility.
type VideoBalancerServer interface {
	GetRedirect(context.Context, *VideoRequest) (*VideoResponse, error)
	mustEmbedUnimplementedVideoBalancerServer()
}

// UnimplementedVideoBalancerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoBalancerServer struct{}

func (UnimplementedVideoBalancerServer) GetRedirect(context.Context, *VideoRequest) (*VideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedirect not implemented")
}
func (UnimplementedVideoBalancerServer) mustEmbedUnimplementedVideoBalancerServer() {}
func (UnimplementedVideoBalancerServer) testEmbeddedByValue()                       {}

// UnsafeVideoBalancerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoBalancerServer will
// result in compilation errors.
type UnsafeVideoBalancerServer interface {
	mustEmbedUnimplementedVideoBalancerServer()
}

func RegisterVideoBalancerServer(s grpc.ServiceRegistrar, srv VideoBalancerServer) {
	// If the following call pancis, it indicates UnimplementedVideoBalancerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoBalancer_ServiceDesc, srv)
}

func _VideoBalancer_GetRedirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBalancerServer).GetRedirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoBalancer_GetRedirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBalancerServer).GetRedirect(ctx, req.(*VideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoBalancer_ServiceDesc is the grpc.ServiceDesc for VideoBalancer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoBalancer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "balancer.VideoBalancer",
	HandlerType: (*VideoBalancerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRedirect",
			Handler:    _VideoBalancer_GetRedirect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/balancer.proto",
}
