// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: balancer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         string                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRequest) Reset() {
	*x = VideoRequest{}
	mi := &file_balancer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRequest) ProtoMessage() {}

func (x *VideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balancer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRequest.ProtoReflect.Descriptor instead.
func (*VideoRequest) Descriptor() ([]byte, []int) {
	return file_balancer_proto_rawDescGZIP(), []int{0}
}

func (x *VideoRequest) GetVideo() string {
	if x != nil {
		return x.Video
	}
	return ""
}

type VideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	mi := &file_balancer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balancer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_balancer_proto_rawDescGZIP(), []int{1}
}

func (x *VideoResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

var File_balancer_proto protoreflect.FileDescriptor

const file_balancer_proto_rawDesc = "" +
	"\n" +
	"\x0ebalancer.proto\x12\bbalancer\"$\n" +
	"\fVideoRequest\x12\x14\n" +
	"\x05video\x18\x01 \x01(\tR\x05video\"2\n" +
	"\rVideoResponse\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl2O\n" +
	"\rVideoBalancer\x12>\n" +
	"\vGetRedirect\x12\x16.balancer.VideoRequest\x1a\x17.balancer.VideoResponseB5Z3github.com/xodiumx/test_task_nmg/src/proto;balancerb\x06proto3"

var (
	file_balancer_proto_rawDescOnce sync.Once
	file_balancer_proto_rawDescData []byte
)

func file_balancer_proto_rawDescGZIP() []byte {
	file_balancer_proto_rawDescOnce.Do(func() {
		file_balancer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balancer_proto_rawDesc), len(file_balancer_proto_rawDesc)))
	})
	return file_balancer_proto_rawDescData
}

var file_balancer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_balancer_proto_goTypes = []any{
	(*VideoRequest)(nil),  // 0: balancer.VideoRequest
	(*VideoResponse)(nil), // 1: balancer.VideoResponse
}
var file_balancer_proto_depIdxs = []int32{
	0, // 0: balancer.VideoBalancer.GetRedirect:input_type -> balancer.VideoRequest
	1, // 1: balancer.VideoBalancer.GetRedirect:output_type -> balancer.VideoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_balancer_proto_init() }
func file_balancer_proto_init() {
	if File_balancer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balancer_proto_rawDesc), len(file_balancer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balancer_proto_goTypes,
		DependencyIndexes: file_balancer_proto_depIdxs,
		MessageInfos:      file_balancer_proto_msgTypes,
	}.Build()
	File_balancer_proto = out.File
	file_balancer_proto_goTypes = nil
	file_balancer_proto_depIdxs = nil
}
