version: '3.9'

services:
  balancer:
    build:
      context: ../../
      dockerfile: ./dev/docker/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - "./.env"
    restart: unless-stopped

  gateway:
    build:
      context: ../../
      dockerfile: ./dev/docker/Dockerfile.gateway
    container_name: gateway
    depends_on:
      - balancer
    ports:
      - "8080:8080"
    env_file:
      - "./.env"
    restart: unless-stopped
